LogsMail:
        Type: AWS::DynamoDB::Table
        Properties:
                TableName: ${self:provider.stage}-logs_mail
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                        - AttributeName: id
                          AttributeType: S
                        - AttributeName: email # match this
                          AttributeType: S
                KeySchema:
                        - AttributeName: id
                          KeyType: HASH
                GlobalSecondaryIndexes:
                        - IndexName: emailGSI
                          KeySchema:
                                  - AttributeName: email # with this
                                    KeyType: HASH
                          Projection:
                                  ProjectionType: ALL
                StreamSpecification:
                        StreamViewType: NEW_AND_OLD_IMAGES
                PointInTimeRecoverySpecification:
                        PointInTimeRecoveryEnabled: true
                Tags: ${self:custom.dynamoTag}

